apiVersion: v1
kind: Service
metadata:
  name: {{ include "stdapp.fullname" . }}
  labels:
    {{- include "stdapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.ports -}}
    {{- if and $port.enabled (or $port.exposeInService (not (hasKey $port "exposeInService"))) }}
    - port: {{ $port.port }}
      name: {{ $name }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "stdapp.selectorLabels" . | nindent 4 }}
