---
  name: testing

  on:
    push:
      branches:
        - "**"
        #- "!main"
      
  jobs:
    test-chart:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Start Minikube
          id: minikube
          uses: medyagh/setup-minikube@latest
        - name: Setup helm
          uses: azure/setup-helm@v4.2.0
          with:
            version: 'latest'
          id: install
        - name: Test charts
          run: ./test-charts.sh
